services:
  postgres: 
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: scraper
      POSTGRES_PASSWORD: scraper
      POSTGRES_DB: scraperdb
    ports: 
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    images: redis
    restart: always
    ports:
     - '6379:6379'

volumes:
  pgdata:
